<?php

namespace Vostre\LocalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BairroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BairroRepository extends EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        
//        $subqueryEmpresa = $this->createQueryBuilder('l1')
//                ->select('IDENTITY(e.bairro)')
//                ->from("CircularSiteBundle:Empresa", 'e')
//                ->where('e.status = 0')
//                ->getDQL();
//        
//        $subqueryParada = $this->createQueryBuilder('l2')
//                ->select('IDENTITY(p.bairro)')
//                ->from("CircularSiteBundle:Parada", 'p')
//                ->where('p.status = 0')
//                ->getDQL();
//        
//        $subqueryItinerarioPartida = $this->createQueryBuilder('l3')
//                ->select('IDENTITY(i.partida)')
//                ->from("CircularSiteBundle:Itinerario", 'i')
//                ->where('i.status = 0')
//                ->getDQL();
//        
//        $subqueryItinerarioDestino = $this->createQueryBuilder('l4')
//                ->select('IDENTITY(i2.destino)')
//                ->from("CircularSiteBundle:Itinerario", 'i2')
//                ->where('i2.status = 0')
//                ->getDQL();
        
        $qb = $this->createQueryBuilder('b')
                ->select('b.id, b.nome, b.status, l.id AS local')
                ->distinct()
                ->leftJoin("VostreLocalBundle:Local", "l", "WITH", "l.id = b.local")
//                ->where($this->createQueryBuilder('e2')->expr()->in('b.id', $subqueryEmpresa))
//                ->orWhere($this->createQueryBuilder('e3')->expr()->in('b.id', $subqueryParada))
//                ->orWhere($this->createQueryBuilder('e4')->expr()->in('b.id', $subqueryItinerarioPartida))
//                ->orWhere($this->createQueryBuilder('e5')->expr()->in('b.id', $subqueryItinerarioDestino))
                ->andWhere("b.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('b.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
