<?php

namespace Vostre\LocalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalRepository extends EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        
//        $subquery = $this->createQueryBuilder('l1')
//                ->select('IDENTITY(b.local)')
//                ->from("VostreLocalBundle:Bairro", 'b')
//                ->where('b.status = 0')
//                ->getDQL();
        
        $qb = $this->createQueryBuilder('l')
                ->select('l.id, l.nome, l.tipo, l.status, e.id AS estado, c.id AS cidade')
                ->distinct()
                ->leftJoin("VostreLocalBundle:Estado", "e", "WITH", "e.id = l.estado")
                ->leftJoin("VostreLocalBundle:Local", "c", "WITH", "c.id = l.cidade")
//                ->where($this->createQueryBuilder('e2')->expr()->in('l.id', $subquery))
                ->andWhere("l.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('l.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
