<?php

namespace Vostre\LocalBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisRepository extends EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        
//        $subquery = $this->createQueryBuilder('e1')
//                ->select('IDENTITY(e.pais)')
//                ->from("VostreLocalBundle:Estado", 'e')
//                ->where('e.status = 0')
//                ->getDQL();
        
        $qb = $this->createQueryBuilder('p')
                ->select(array('p'))
                ->distinct()
//                ->where($this->createQueryBuilder('e2')->expr()->in('p.id', $subquery))
                ->andWhere("p.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('p.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
