<?php

namespace Vostre\CentralBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChamadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoRepository extends EntityRepository
{
}
