<?php

namespace Vostre\CentralBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProdutoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutoClienteRepository extends EntityRepository
{
}
