<?php

namespace Vostre\CentralBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecadoRepository extends EntityRepository
{
}
