<?php

namespace Vostre\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoRepository extends EntityRepository
{
    
    public function listarUltimosContatos($limite = null){
        $qb = $this->createQueryBuilder('c')
//                ->select('b.id, b.nome, b.status, l.id AS local')
                ->select('c')
                ->distinct()
                ->addOrderBy('c.dataCadastro', 'DESC');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
