<?php

namespace Vostre\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DestaqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestaqueRepository extends EntityRepository
{
    
    public function listarTodos($soAtivos = true, $tipo = 2){
        
        // tipos: 0 -> destaque | 1: carrossel | 2: ambos
        
        if($soAtivos){
            
            if($tipo != 2){
                $qb = $this->createQueryBuilder('d')
                ->select('d')
                ->andWhere('d.situacao = 0')
                ->andWhere('d.carrossel = '.$tipo)
                //->distinct()
                ->addOrderBy('d.ordem', 'ASC');
            } else{
                $qb = $this->createQueryBuilder('d')
                ->select('d')
                ->andWhere('d.situacao = 0')
                //->distinct()
                ->addOrderBy('d.ordem', 'ASC');
            }
            
            
        } else{
            
            if($tipo != 2){
                $qb = $this->createQueryBuilder('d')
                ->select('d')
                ->andWhere('d.carrossel = '.$tipo)
                //->distinct()
                ->addOrderBy('d.ordem', 'ASC');
            } else{
                $qb = $this->createQueryBuilder('d')
                ->select('d')
                //->distinct()
                ->addOrderBy('d.ordem', 'ASC');
            }
            
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
