<?php

namespace Vostre\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends EntityRepository
{
    
    public function listarTodos($soAtivos = true){
        
        if($soAtivos){
            $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->andWhere('p.situacao = 0')
                //->distinct()
                ->addOrderBy('p.dataCadastro', 'DESC');
        } else{
            $qb = $this->createQueryBuilder('p')
                ->select('p')
                //->distinct()
                ->addOrderBy('p.dataCadastro', 'DESC');
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
