<?php

namespace Vostre\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicoRepository extends EntityRepository
{
    
    public function listarTodos($soAtivos = true){
        
        if($soAtivos){
            $qb = $this->createQueryBuilder('s')
                ->select('s')
                ->andWhere('s.situacao = 0')
                //->distinct()
                ->addOrderBy('s.ordem', 'ASC');
        } else{
            $qb = $this->createQueryBuilder('s')
                ->select('s')
                //->distinct()
                ->addOrderBy('s.ordem', 'ASC');
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
