#pais : 
#  type: rest
#  resource:     "CircularSiteBundle:PaisRest"
#  name_prefix:  api_

parada : 
  type: rest
  resource:     "CircularSiteBundle:ParadaRest"
  name_prefix:  api_

itinerario : 
  type: rest
  resource:     "CircularSiteBundle:ItinerarioRest"
  name_prefix:  api_
  
mensagem : 
  type: rest
  resource:     "CircularSiteBundle:MensagemRest"
  name_prefix:  api_

circular_api_get_dados:
    pattern: /circular/recebe-dados/{hash}/{data}
    defaults: {_controller: CircularSiteBundle:CircularRest:getDados}  
  
circular_api_get_dados:
    pattern: /recebe-dados/{hash}/{data}
    defaults: {_controller: CircularSiteBundle:CircularRest:getDados}
    
circular_api_get_paradas:
    pattern: /recebe-dados/paradas/{hash}/{data}
    defaults: {_controller: CircularSiteBundle:ParadaRest:getDados}
    
circular_api_get_mensagens:
    pattern: /recebe-dados/mensagens/{hash}/{data}
    defaults: {_controller: CircularSiteBundle:MensagemRest:getDados}