parameters:
#    circular_site.example.class: Circular\SiteBundle\Example

services:
#    circular_site.example:
#        class: %circular_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
