<?php

namespace Circular\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HorarioItinerarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioItinerarioRepository extends EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('hi')
                ->select('hi.id, h.id AS horario, i.id AS itinerario, hi.domingo, hi.segunda, hi.terca, '
                        . 'hi.quarta, hi.quinta, hi.sexta, hi.sabado, hi.status')
                //->select('p')
                ->distinct()
                ->leftJoin("CircularSiteBundle:Horario", "h", "WITH", "h.id = hi.horario")
                ->leftJoin("CircularSiteBundle:Itinerario", "i", "WITH", "i.id = hi.itinerario")
                ->where("hi.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                //->leftJoin("CircularSiteBundle:ParadaItinerario", "pi", "WITH", "pi.parada = p.id")
                ->addOrderBy('hi.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function invalidaTodosHorariosItinerario($idItinerario){
        
        $qb = $this->createQueryBuilder('hi')
                ->update("CircularSiteBundle:HorarioItinerario", 'hi')
                ->set('hi.status', 2)
                ->set('hi.ultimaAlteracao', ':now')
                ->where('hi.itinerario = :idItinerario')
                ->setParameter('now', new \DateTime())
                ->setParameter('idItinerario', $idItinerario);

        $qb->getQuery()->getResult();
        
        return true;
        
    }

    
}
