<?php

namespace Circular\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioRepository extends EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        
//        $subquery = $this->createQueryBuilder('l1')
//                ->select('IDENTITY(hi.horario)')
//                ->from("CircularSiteBundle:HorarioItinerario", 'hi')
//                ->where('hi.status = 0')
//                ->getDQL();
        
        $qb = $this->createQueryBuilder('h')
                ->select(array('h'))
                ->distinct()
//                ->where($this->createQueryBuilder('e2')->expr()->in('h.id', $subquery))
                ->andWhere("h.ultimaAlteracao > :ultimaAlteracao")
                ->andWhere("h.ultimaAlteracao <= :now")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->setParameter('now', new \DateTime())
                ->addOrderBy('h.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarProximoHorario($limite = null, $itinerario, $hora){
        $qb = $this->createQueryBuilder('h')
                ->select('h')
                //->select('p')
                ->distinct()
                ->leftJoin("CircularSiteBundle:HorarioItinerario", "hi", "WITH", "hi.horario = h.id")
                ->andWhere("hi.itinerario = :itinerario")
                ->andWhere('h.nome > :hora')
                ->setParameter('itinerario', $itinerario)
                ->setParameter('hora', $hora)
                ->addOrderBy('h.nome');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getOneOrNullResult();
        
    }
    
    public function listarPrimeiroHorario($limite = null, $itinerario, $hora){
        $qb = $this->createQueryBuilder('h')
                ->select('h')
                //->select('p')
                ->distinct()
                ->leftJoin("CircularSiteBundle:HorarioItinerario", "hi", "WITH", "hi.horario = h.id")
                ->andWhere("hi.itinerario = :itinerario")
                ->setParameter('itinerario', $itinerario)
                ->addOrderBy('h.nome');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getOneOrNullResult();
        
    }
    
}
