<?php

namespace Circular\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecaoItinerarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecaoItinerarioRepository extends EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('si')
                ->select('si.id, si.ordem, si.nome, si.valor, i.id AS itinerario, si.status')
                //->select('p')
                ->distinct()
                ->leftJoin("CircularSiteBundle:Itinerario", "i", "WITH", "i.id = si.itinerario")
                ->where("si.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                //->leftJoin("CircularSiteBundle:ParadaItinerario", "pi", "WITH", "pi.parada = p.id")
                ->addOrderBy('si.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function invalidaTodasSecoesItinerario($idItinerario){
        
        $qb = $this->createQueryBuilder('si')
                ->update("CircularSiteBundle:SecaoItinerario", 'si')
                ->set('si.status', 2)
                ->set('si.ultimaAlteracao', ':now')
                ->where('si.itinerario = :idItinerario')
                ->setParameter('now', new \DateTime())
                ->setParameter('idItinerario', $idItinerario);

        $qb->getQuery()->getResult();
        
        return true;
        
    }
    
}
