parameters:
#    vostre_site.example.class: Vostre\SiteBundle\Example

services:
#    vostre_site.example:
#        class: %vostre_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
