<?php

namespace Vostre\CRMBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnderecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnderecoRepository extends EntityRepository
{
}
