<?php

namespace Vostre\CRMBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TelefoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefoneRepository extends EntityRepository
{
}
