<?php

namespace Proxies\__CG__\Circular\SiteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DiaHorarioItinerario extends \Circular\SiteBundle\Entity\DiaHorarioItinerario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'horarioItinerario', 'domingo', 'segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'status', 'dataCriacao', 'ultimaAlteracao');
        }

        return array('__isInitialized__', 'horarioItinerario', 'domingo', 'segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'status', 'dataCriacao', 'ultimaAlteracao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DiaHorarioItinerario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomingo($domingo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomingo', array($domingo));

        return parent::setDomingo($domingo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomingo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomingo', array());

        return parent::getDomingo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSegunda($segunda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSegunda', array($segunda));

        return parent::setSegunda($segunda);
    }

    /**
     * {@inheritDoc}
     */
    public function getSegunda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegunda', array());

        return parent::getSegunda();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerca($terca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerca', array($terca));

        return parent::setTerca($terca);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerca', array());

        return parent::getTerca();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuarta($quarta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuarta', array($quarta));

        return parent::setQuarta($quarta);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuarta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuarta', array());

        return parent::getQuarta();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuinta($quinta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuinta', array($quinta));

        return parent::setQuinta($quinta);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuinta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuinta', array());

        return parent::getQuinta();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexta($sexta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexta', array($sexta));

        return parent::setSexta($sexta);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexta', array());

        return parent::getSexta();
    }

    /**
     * {@inheritDoc}
     */
    public function setSabado($sabado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSabado', array($sabado));

        return parent::setSabado($sabado);
    }

    /**
     * {@inheritDoc}
     */
    public function getSabado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSabado', array());

        return parent::getSabado();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCriacao($dataCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCriacao', array($dataCriacao));

        return parent::setDataCriacao($dataCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimaAlteracao($ultimaAlteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimaAlteracao', array($ultimaAlteracao));

        return parent::setUltimaAlteracao($ultimaAlteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimaAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimaAlteracao', array());

        return parent::getUltimaAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioItinerario(\Circular\SiteBundle\Entity\HorarioItinerario $horarioItinerario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioItinerario', array($horarioItinerario));

        return parent::setHorarioItinerario($horarioItinerario);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioItinerario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioItinerario', array());

        return parent::getHorarioItinerario();
    }

}
