vostre_site_central_cliente_home:
    pattern:  /central-do-cliente/home
    defaults: { _controller: VostreCentralBundle:Central:index }
    
vostre_site_admin_paises:
    pattern:  /central-do-cliente/home/paises
    defaults: { _controller: VostreCentralBundle:Central:indexPais }
    
vostre_site_admin_paises_cadastra:
    pattern:  /central-do-cliente/home/paises/cadastra/{id_pais}
    defaults: { _controller: VostreLocalBundle:Pais:cadastrar, id_pais: -1 }
    requirements:
        _method: POST
        
vostre_site_admin_estados:
    pattern:  /central-do-cliente/home/estados
    defaults: { _controller: VostreCentralBundle:Central:indexEstado }
    
vostre_site_admin_estados_cadastra:
    pattern:  /central-do-cliente/home/estados/cadastra/{id_estado}
    defaults: { _controller: VostreLocalBundle:Estado:cadastrar, id_estado: -1 }
    requirements:
        _method: POST
        
vostre_site_admin_locais:
    pattern:  /central-do-cliente/home/locais
    defaults: { _controller: VostreCentralBundle:Central:indexLocal }
    
vostre_site_admin_locais_cadastra:
    pattern:  /central-do-cliente/home/locais/cadastra/{id_local}
    defaults: { _controller: VostreLocalBundle:Local:cadastrar, id_local: -1 }
    requirements:
        _method: POST
        
circular_site_admin_locais_form:
    pattern: /local/form/{id_local}
    defaults: {_controller: VostreLocalBundle:Local:form, id_local: -1}
        
vostre_site_admin_bairros:
    pattern:  /central-do-cliente/home/bairros
    defaults: { _controller: VostreCentralBundle:Central:indexBairro }
    
vostre_site_admin_bairros_cadastra:
    pattern:  /central-do-cliente/home/bairros/cadastra/{id_bairro}
    defaults: { _controller: VostreLocalBundle:Bairro:cadastrar, id_bairro: -1 }
    requirements:
        _method: POST
        
circular_site_admin_bairros_form:
    pattern: /bairro/form/{id_bairro}
    defaults: {_controller: VostreLocalBundle:Bairro:form, id_bairro: -1}
        
vostre_site_admin_contato_exclui:
    pattern:  /central-do-cliente/home/contatos/exclui/{id_contato}
    defaults: { _controller: VostreCentralBundle:Central:excluirContato, id_contato: -1 }
    requirements:
        _method: POST
        
vostre_site_admin_contato_carrega:
    pattern:  /central-do-cliente/home/contatos/carrega/{id_contato}
    defaults: { _controller: VostreCentralBundle:Central:carregarContato, id_contato: -1 }
    requirements:
        _method: GET
        
vostre_site_admin_acessos_carrega:
    pattern:  /central-do-cliente/home/token/carrega/{identificador}
    defaults: { _controller: VostreCentralBundle:Central:carregaAcessoPorIdentificador, identificador: -1 }
    requirements:
        _method: GET
        
vostre_site_admin_mensagem_carrega:
    pattern:  /central-do-cliente/home/mensagem/carrega/{id_mensagem}
    defaults: { _controller: VostreCentralBundle:Central:carregarMensagem, id_mensagem: -1 }
    requirements:
        _method: GET

######################## CONTEUDO SITE ###############################
        
vostre_site_admin_destaques:
    pattern:  /central-do-cliente/home/destaques
    defaults: { _controller: VostreSiteBundle:Destaque:indexDestaque }
    
vostre_site_admin_destaques_cadastra:
    pattern:  /central-do-cliente/home/destaques/cadastra/{id_destaque}
    defaults: { _controller: VostreSiteBundle:Destaque:cadastrar, id_destaque: -1 }
    requirements:
        _method: POST
        
######################## FIM CONTEUDO SITE ###############################

######################## CIRCULAR ###############################

circular_api_get_token:
    pattern: /api/token
    defaults: {_controller: CircularSiteBundle:CircularRest:getToken}        
        
circular_site_admin_horarios:
    pattern:  /central-do-cliente/home/horarios
    defaults: { _controller: CircularSiteBundle:Admin:indexHorario }
    
circular_site_admin_horarios_cadastra:
    pattern:  /central-do-cliente/home/horarios/cadastra/{id_horario}
    defaults: { _controller: CircularSiteBundle:Horario:cadastrar, id_horario: -1 }
    requirements:
        _method: POST
        
circular_site_admin_paradas:
    pattern:  /central-do-cliente/home/paradas
    defaults: { _controller: CircularSiteBundle:Admin:indexParada }
    
circular_site_admin_paradas_form:
    pattern:  /central-do-cliente/home/paradas/form/{id_parada}
    defaults: { _controller: CircularSiteBundle:Parada:form, id_parada: -1 }
    
circular_site_admin_paradas_cadastra:
    pattern:  /central-do-cliente/home/paradas/cadastra/{id_parada}
    defaults: { _controller: CircularSiteBundle:Parada:cadastrar, id_parada: -1 }
    requirements:
        _method: POST

circular_site_admin_empresas:
    pattern:  /central-do-cliente/home/empresas
    defaults: { _controller: CircularSiteBundle:Admin:indexEmpresa }
    
circular_site_admin_empresas_form:
    pattern:  /central-do-cliente/home/empresas/form/{id_empresa}
    defaults: { _controller: CircularSiteBundle:Empresa:form, id_empresa: -1 }
    
circular_site_admin_empresas_cadastra:
    pattern:  /central-do-cliente/home/empresas/cadastra/{id_empresa}
    defaults: { _controller: CircularSiteBundle:Empresa:cadastrar, id_empresa: -1 }
    requirements:
        _method: POST
        
circular_site_admin_itinerarios:
    pattern:  /central-do-cliente/home/itinerarios
    defaults: { _controller: CircularSiteBundle:Admin:indexItinerario }
    
circular_site_admin_itinerarios_cadastra:
    pattern:  /central-do-cliente/home/itinerarios/cadastra/{id_itinerario}
    defaults: { _controller: CircularSiteBundle:Itinerario:cadastrar, id_itinerario: -1 }
    requirements:
        _method: POST
        
circular_site_admin_itinerarios_carrega:
    pattern:  /central-do-cliente/home/itinerarios/carrega/{id_itinerario}
    defaults: { _controller: CircularSiteBundle:Itinerario:carregar, id_itinerario: -1 }
    requirements:
        _method: GET|POST
        
circular_site_admin_itinerarios_edita:
    pattern:  /central-do-cliente/home/itinerarios/edita/{id_itinerario}
    defaults: { _controller: CircularSiteBundle:Itinerario:editar, id_itinerario: -1 }
    requirements:
        _method: POST
        
circular_site_admin_itinerarios_edita_tarifa:
    pattern:  /central-do-cliente/home/itinerarios/tarifa/edita
    defaults: { _controller: CircularSiteBundle:Itinerario:editarTarifa }
    requirements:
        _method: GET|POST
        
circular_site_admin_horarios_itinerarios:
    pattern:  /central-do-cliente/home/horarios-itinerarios
    defaults: { _controller: CircularSiteBundle:Admin:indexHorarioItinerario }
    
circular_site_admin_horarios_itinerarios_cadastra:
    pattern:  /central-do-cliente/home/horarios-itinerarios/cadastra/{id_horario_itinerario}
    defaults: { _controller: CircularSiteBundle:HorarioItinerario:cadastrar, id_horario_itinerario: -1 }
    requirements:
        _method: POST
        
circular_site_admin_horarios_itinerarios_carrega:
    pattern:  /central-do-cliente/home/horarios-itinerarios/carrega/{idItinerario}
    defaults: { _controller: CircularSiteBundle:HorarioItinerario:carregar, idItinerario: -1 }
    requirements:
        _method: GET|POST
        
circular_site_admin_horarios_itinerarios_edita:
    pattern:  /central-do-cliente/home/horarios-itinerarios/edita/{id_horario_itinerario}
    defaults: { _controller: CircularSiteBundle:HorarioItinerario:editar, id_horario_itinerario: -1 }
    requirements:
        _method: POST
        
circular_site_admin_mensagens:
    pattern:  /central-do-cliente/home/mensagens
    defaults: { _controller: CircularSiteBundle:Admin:indexMensagem }
    
circular_site_admin_mensagens_form:
    pattern:  /central-do-cliente/home/mensagens/form/{id_mensagem}
    defaults: { _controller: CircularSiteBundle:Mensagem:form, id_mensagem: -1 }
    
circular_site_admin_mensagens_cadastra:
    pattern:  /central-do-cliente/home/mensagens/cadastra/{id_mensagem}
    defaults: { _controller: CircularSiteBundle:Mensagem:cadastrar, id_mensagem: -1 }
    requirements:
        _method: POST
        
circular_site_admin_secoes_itinerarios:
    pattern:  /central-do-cliente/home/secoes-itinerarios
    defaults: { _controller: CircularSiteBundle:Admin:indexSecaoItinerario }
    
circular_site_admin_secoes_itinerarios_carrega:
    pattern:  /central-do-cliente/home/secoes-itinerarios/carrega/{idItinerario}
    defaults: { _controller: CircularSiteBundle:SecaoItinerario:carregar, idItinerario: -1 }
    requirements:
        _method: GET|POST
        
circular_site_admin_secoes_itinerarios_edita:
    pattern:  /central-do-cliente/home/secoes-itinerarios/edita/{idItinerario}
    defaults: { _controller: CircularSiteBundle:SecaoItinerario:editar, idItinerario: -1 }
    requirements:
        _method: POST
        
######################## FIM CIRCULAR ###############################