parameters:
#    vostre_central.example.class: Vostre\CentralBundle\Example

services:
#    vostre_central.example:
#        class: %vostre_central.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
